server:
  port: 8001

spring:
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 112.74.75.182
      port: 6379
  #      password: 123456

  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  stats:
    locale:
      a-map-key: 824c511f0997586ea016f979fdb23087

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
