server:
  port: 8001

spring:
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 112.74.75.182
      port: 6379
  #      password: 123456
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'

  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  stats:
    locale:
      a-map-key: 824c511f0997586ea016f979fdb23087
  domain:
    default: air.com:8001
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - baidu.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
